### ISSUE TITLE
Error in extensions tab

### ISSUE THREAD

**Issue by TheDjRider** [marttiphpbb/phpbb-ext-codemirror#2]
When try to open extensions/CodeMirror tab give me this error:

> Fatal error: Uncaught Twig\Error\LoaderError: Unable to find template "@marttiphpbb_codemirror/addon/fullscreen.js" (looked into: /home/eternaln/forum.eternalnetworktm.com/ext/marttiphpbb/codemirror/adm/style, /home/eternaln/forum.eternalnetworktm.com/ext/marttiphpbb/codemirror/styles/all/template) in "@marttiphpbb_codemirror/include/codemirror.html" at line 14. in /home/eternaln/forum.eternalnetworktm.com/vendor/twig/twig/src/Loader/FilesystemLoader.php:250 Stack trace: #0 /home/eternaln/forum.eternalnetworktm.com/phpbb/template/twig/loader.php(135): Twig\Loader\FilesystemLoader->findTemplate('@marttiphpbb_co...', true) #1 /home/eternaln/forum.eternalnetworktm.com/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate('@marttiphpbb_co...') #2 /home/eternaln/forum.eternalnetworktm.com/phpbb/template/twig/environment.php(328): Twig\Loader\FilesystemLoader->getCacheKey('@marttiphpbb_co...') #3 /home/eternaln/forum.eternalnetworktm.com/cache/production/twig/ca/ca0bd7bde2c6eaac453b48d0 in /home/eternaln/forum.eternalnetworktm.com/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 250

**Comment by marttiphpbb** [comment]
So isn't the file present in your setup?  
Didn't you install the file [ `/ext/marttiphpbb/styles/all/template/addon/fullscreen.js`](https://github.com/marttiphpbb/phpbb-ext-codemirror/blob/master/styles/all/template/addon/fullscreen.js)?
